build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
checks:
    php: true
filter:
    excluded_paths:
        - "tests/"
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
