#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Rudra\Cli\Console;

parse_str(implode('&', array_slice($argv, 1)), $inputArgs);

$console = new Console();
$console->printer(" RUDRA CONSOLE: ", "white", "green");
$console->addCommand(1, [\Rudra\Cli\Tests\App\Command\TestCommand::class]);
$console->addCommand(2, [\Rudra\Cli\Tests\App\Command\TestCommand::class, "actionSecond"]);

$console->run($inputArgs);
